parameters:
services:
    elastica:
        class: Elastica\Client
        arguments:
            - { host: "%elasticsearch.host%", port: %elasticsearch.port% }
        tags:
            - { name: elasticsearch.extension }
    offer_fr_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.offer_index.fr%", "%elasticsearch.type%", %index%, %offer%]
        tags:
            - { name: elasticsearch.extension }
    general_fr_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.offer_index.fr%", "%elasticsearch.type_general%", %index%, %general%]
        tags:
            - { name: elasticsearch.extension }
    offer_de_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.offer_index.de%", "%elasticsearch.type%", %index%, %offer%]
        tags:
            - { name: elasticsearch.extension }
    general_de_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.general_index.de%", "%elasticsearch.type_general%", %index%, %general%]
        tags:
            - { name: elasticsearch.extension }
    offer_es_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.offer_index.es%", "%elasticsearch.type%", %index%, %offer%]
        tags:
            - { name: elasticsearch.extension }
    general_es_index:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexManager
        arguments: [@elastica, "%elasticsearch.general_index.es%", "%elasticsearch.type_general%", %index%, %general%]
        tags:
            - { name: elasticsearch.extension }
    offer_fr_data:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexDataCollector
        arguments: [@elastica, "%elasticsearch.offer_index.fr%", "%elasticsearch.general_index.fr%", "%elasticsearch.type%", "%elasticsearch.type_general%"]
        tags:
            - { name: elasticsearch.extension }
    offer_de_data:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexDataCollector
        arguments: [@elastica, "%elasticsearch.offer_index.de%", "%elasticsearch.general_index.de%", "%elasticsearch.type%", "%elasticsearch.type_general%"]
        tags:
            - { name: elasticsearch.extension }
    offer_es_data:
        class: Aramis\Bundle\ElasticsearchBundle\Services\IndexDataCollector
        arguments: [@elastica, "%elasticsearch.offer_index.es%", "%elasticsearch.general_index.es%", "%elasticsearch.type%", "%elasticsearch.type_general%"]
        tags:
            - { name: elasticsearch.extension }

    rabbitmq.client:
        class: Aramis\Bundle\ElasticsearchBundle\RabbitMq\RabbitMqClient
        arguments: [%rabbitmq%]
    rabbitmq.river:
        class: Aramis\Bundle\ElasticsearchBundle\RabbitMq\RabbitMqRiver
        arguments: [@rabbitmq.client, %elasticsearch%, %river%, %indexes%, "%elasticsearch.type%", @doctrine.dbal.default_connection, @tools]
