parameters:
services:
    aramis_elasticsearch_builder:
        class: Aramis\Bundle\ElasticsearchBundle\Index\IndexBuilder
        arguments:
            - @service_container
            - { host: "%aramis_elasticsearch.elasticsearch.host%", port: %aramis_elasticsearch.elasticsearch.port% }
            - %aramis_elasticsearch.data_providers%
    data_provider_example:
        class: Aramis\Bundle\ElasticsearchBundle\Provider\DataProviderExample
